//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class newdbEntities1 : DbContext
    {
        public newdbEntities1()
            : base("name=newdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbstudent> tbstudents { get; set; }
        public virtual DbSet<tbstudentfee> tbstudentfees { get; set; }
        public virtual DbSet<tbstudentinfo> tbstudentinfoes { get; set; }
    }
}
