//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbstudentinfo
    {
        public int StudentInfoID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> SchoolLeavingDate { get; set; }
    
        public virtual tbstudent tbstudent { get; set; }
    }
}
